# Generated by Django 5.2.17 on 2026-09-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_app_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'verbose_name': 'Приложения', 'verbose_name_plural': 'Приложения'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
    ]
