# Generated by Django 5.2.17 on 2026-09-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_app_options_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
