# Generated by Django 5.2.17 on 2026-09-14 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_app_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='slug',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('stars', models.PositiveSmallIntegerField(default=5)),
                ('recommended', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.app')),
            ],
        ),
    ]
